const problems=[
    {
        solution:[
            '2','5','9','6','1','8','3','4','7',
            '8','3','1','2','4','7','9','6','5',
            '4','6','7','5','9','3','2','1','8',
            '9','8','4','3','6','1','5','7','2',
            '3','2','5','8','7','4','6','9','1',
            '1','7','6','9','2','5','4','8','3',
            '5','9','8','7','3','6','1','2','4',
            '7','1','2','4','5','9','8','3','6',
            '6','4','3','1','8','2','7','5','9'
        ],
        game: [
            {idx:0,lock:false, zone:0,row:0,col:0,draft:['','','','','','','','',''],answer:''},{idx:1,lock:false, zone:0,row:0,col:1,draft:['','','','','','','','',''],answer:''},{idx:2,lock:false, zone:0,row:0,col:2,draft:['','','','','','','','',''],answer:''},{idx:3,lock:false, zone:1,row:0,col:3,draft:['','','','','','','','',''],answer:''},{idx:4,lock:true, zone:1,row:0,col:4,draft:['','','','','','','','',''],answer:'1'},{idx:5,lock:false, zone:1,row:0,col:5,draft:['','','','','','','','',''],answer:''},{idx:6,lock:false, zone:2,row:0,col:6,draft:['','','','','','','','',''],answer:''},{idx:7,lock:false, zone:2,row:0,col:7,draft:['','','','','','','','',''],answer:''},{idx:8,lock:false, zone:2,row:0,col:8,draft:['','','','','','','','',''],answer:''},
            {idx:9,lock:false, zone:0,row:1,col:0,draft:['','','','','','','','',''],answer:''},{idx:10,lock:true, zone:0,row:1,col:1,draft:['','','','','','','','',''],answer:'3'},{idx:11,lock:true, zone:0,row:1,col:2,draft:['','','','','','','','',''],answer:'1'},{idx:12,lock:true, zone:1,row:1,col:3,draft:['','','','','','','','',''],answer:'2'},{idx:13,lock:false, zone:1,row:1,col:4,draft:['','','','','','','','',''],answer:''},{idx:14,lock:true, zone:1,row:1,col:5,draft:['','','','','','','','',''],answer:'7'},{idx:15,lock:false, zone:2,row:1,col:6,draft:['','','','','','','','',''],answer:''},{idx:16,lock:true, zone:2,row:1,col:7,draft:['','','','','','','','',''],answer:'6'},{idx:17,lock:false, zone:2,row:1,col:8,draft:['','','','','','','','',''],answer:''},
            {idx:18,lock:true, zone:0,row:2,col:0,draft:['','','','','','','','',''],answer:'4'},{idx:19,lock:false, zone:0,row:2,col:1,draft:['','','','','','','','',''],answer:''},{idx:20,lock:false, zone:0,row:2,col:2,draft:['','','','','','','','',''],answer:''},{idx:21,lock:true, zone:1,row:2,col:3,draft:['','','','','','','','',''],answer:'5'},{idx:22,lock:false, zone:1,row:2,col:4,draft:['','','','','','','','',''],answer:''},{idx:23,lock:false, zone:1,row:2,col:5,draft:['','','','','','','','',''],answer:''},{idx:24,lock:false, zone:2,row:2,col:6,draft:['','','','','','','','',''],answer:''},{idx:25,lock:false, zone:2,row:2,col:7,draft:['','','','','','','','',''],answer:''},{idx:26,lock:true, zone:2,row:2,col:8,draft:['','','','','','','','',''],answer:'8'},
            {idx:27,lock:true, zone:3,row:3,col:0,draft:['','','','','','','','',''],answer:'9'},{idx:28,lock:false, zone:3,row:3,col:1,draft:['','','','','','','','',''],answer:''},{idx:29,lock:false, zone:3,row:3,col:2,draft:['','','','','','','','',''],answer:''},{idx:30,lock:false, zone:4,row:3,col:3,draft:['','','','','','','','',''],answer:''},{idx:31,lock:false, zone:4,row:3,col:4,draft:['','','','','','','','',''],answer:''},{idx:32,lock:false, zone:4,row:3,col:5,draft:['','','','','','','','',''],answer:''},{idx:33,lock:false, zone:5,row:3,col:6,draft:['','','','','','','','',''],answer:''},{idx:34,lock:false, zone:5,row:3,col:7,draft:['','','','','','','','',''],answer:''},{idx:35,lock:true, zone:5,row:3,col:8,draft:['','','','','','','','',''],answer:'2'},
            {idx:36,lock:false, zone:3,row:4,col:0,draft:['','','','','','','','',''],answer:''},{idx:37,lock:true, zone:3,row:4,col:1,draft:['','','','','','','','',''],answer:'2'},{idx:38,lock:true, zone:3,row:4,col:2,draft:['','','','','','','','',''],answer:'5'},{idx:39,lock:true, zone:4,row:4,col:3,draft:['','','','','','','','',''],answer:'8'},{idx:40,lock:true, zone:4,row:4,col:4,draft:['','','','','','','','',''],answer:'7'},{idx:41,lock:false, zone:4,row:4,col:5,draft:['','','','','','','','',''],answer:''},{idx:42,lock:false, zone:5,row:4,col:6,draft:['','','','','','','','',''],answer:''},{idx:43,lock:false, zone:5,row:4,col:7,draft:['','','','','','','','',''],answer:''},{idx:44,lock:true, zone:5,row:4,col:8,draft:['','','','','','','','',''],answer:'1'},
            {idx:45,lock:false, zone:3,row:5,col:0,draft:['','','','','','','','',''],answer:''},{idx:46,lock:true, zone:3,row:5,col:1,draft:['','','','','','','','',''],answer:'7'},{idx:47,lock:false, zone:3,row:5,col:2,draft:['','','','','','','','',''],answer:''},{idx:48,lock:false, zone:4,row:5,col:3,draft:['','','','','','','','',''],answer:''},{idx:49,lock:false, zone:4,row:5,col:4,draft:['','','','','','','','',''],answer:''},{idx:50,lock:true, zone:4,row:5,col:5,draft:['','','','','','','','',''],answer:'5'},{idx:51,lock:true, zone:5,row:5,col:6,draft:['','','','','','','','',''],answer:'4'},{idx:52,lock:false, zone:5,row:5,col:7,draft:['','','','','','','','',''],answer:''},{idx:53,lock:false, zone:5,row:5,col:8,draft:['','','','','','','','',''],answer:''},
            {idx:54,lock:true, zone:6,row:6,col:0,draft:['','','','','','','','',''],answer:'5'},{idx:55,lock:false, zone:6,row:6,col:1,draft:['','','','','','','','',''],answer:''},{idx:56,lock:true, zone:6,row:6,col:2,draft:['','','','','','','','',''],answer:'8'},{idx:57,lock:false, zone:7,row:6,col:3,draft:['','','','','','','','',''],answer:''},{idx:58,lock:false, zone:7,row:6,col:4,draft:['','','','','','','','',''],answer:''},{idx:59,lock:false, zone:7,row:6,col:5,draft:['','','','','','','','',''],answer:''},{idx:60,lock:false, zone:8,row:6,col:6,draft:['','','','','','','','',''],answer:''},{idx:61,lock:true, zone:8,row:6,col:7,draft:['','','','','','','','',''],answer:'2'},{idx:62,lock:false, zone:8,row:6,col:8,draft:['','','','','','','','',''],answer:''},
            {idx:63,lock:false, zone:6,row:7,col:0,draft:['','','','','','','','',''],answer:''},{idx:64,lock:false, zone:6,row:7,col:1,draft:['','','','','','','','',''],answer:''},{idx:65,lock:false, zone:6,row:7,col:2,draft:['','','','','','','','',''],answer:''},{idx:66,lock:false, zone:7,row:7,col:3,draft:['','','','','','','','',''],answer:''},{idx:67,lock:false, zone:7,row:7,col:4,draft:['','','','','','','','',''],answer:''},{idx:68,lock:false, zone:7,row:7,col:5,draft:['','','','','','','','',''],answer:''},{idx:69,lock:false, zone:8,row:7,col:6,draft:['','','','','','','','',''],answer:''},{idx:70,lock:false, zone:8,row:7,col:7,draft:['','','','','','','','',''],answer:''},{idx:71,lock:false, zone:8,row:7,col:8,draft:['','','','','','','','',''],answer:''},
            {idx:72,lock:false, zone:6,row:8,col:0,draft:['','','','','','','','',''],answer:''},{idx:73,lock:true, zone:6,row:8,col:1,draft:['','','','','','','','',''],answer:'4'},{idx:74,lock:false, zone:6,row:8,col:2,draft:['','','','','','','','',''],answer:''},{idx:75,lock:false, zone:7,row:8,col:3,draft:['','','','','','','','',''],answer:''},{idx:76,lock:false, zone:7,row:8,col:4,draft:['','','','','','','','',''],answer:''},{idx:77,lock:false, zone:7,row:8,col:5,draft:['','','','','','','','',''],answer:''},{idx:78,lock:true, zone:8,row:8,col:6,draft:['','','','','','','','',''],answer:'7'},{idx:79,lock:false, zone:8,row:8,col:7,draft:['','','','','','','','',''],answer:''},{idx:80,lock:false, zone:8,row:8,col:8,draft:['','','','','','','','',''],answer:''},
        ]
    },
    {solution:[
        '3','8','1','9','2','7','5','6','4',
        '4','5','2','6','1','8','3','7','9',
        '7','6','9','4','5','3','1','2','8',
        '1','9','8','7','3','6','2','4','5',
        '2','4','7','1','9','5','6','8','3',
        '6','3','5','8','4','2','7','9','1',
        '8','2','3','5','7','4','9','1','6',
        '9','7','4','3','6','1','8','5','2',
        '5','1','6','2','8','9','4','3','7'
    ],
    game: [
        {idx:0,lock:false, zone:0,row:0,col:0,draft:['','','','','','','','',''],answer:''},{idx:1,lock:false, zone:0,row:0,col:1,draft:['','','','','','','','',''],answer:''},{idx:2,lock:true, zone:0,row:0,col:2,draft:['','','','','','','','',''],answer:'1'},{idx:3,lock:false, zone:1,row:0,col:3,draft:['','','','','','','','',''],answer:''},{idx:4,lock:false, zone:1,row:0,col:4,draft:['','','','','','','','',''],answer:''},{idx:5,lock:true, zone:1,row:0,col:5,draft:['','','','','','','','',''],answer:'7'},{idx:6,lock:false, zone:2,row:0,col:6,draft:['','','','','','','','',''],answer:''},{idx:7,lock:false, zone:2,row:0,col:7,draft:['','','','','','','','',''],answer:''},{idx:8,lock:false, zone:2,row:0,col:8,draft:['','','','','','','','',''],answer:''},
        {idx:9,lock:false, zone:0,row:1,col:0,draft:['','','','','','','','',''],answer:''},{idx:10,lock:false, zone:0,row:1,col:1,draft:['','','','','','','','',''],answer:''},{idx:11,lock:true, zone:0,row:1,col:2,draft:['','','','','','','','',''],answer:'2'},{idx:12,lock:true, zone:1,row:1,col:3,draft:['','','','','','','','',''],answer:'6'},{idx:13,lock:false, zone:1,row:1,col:4,draft:['','','','','','','','',''],answer:''},{idx:14,lock:false, zone:1,row:1,col:5,draft:['','','','','','','','',''],answer:''},{idx:15,lock:true, zone:2,row:1,col:6,draft:['','','','','','','','',''],answer:'3'},{idx:16,lock:false, zone:2,row:1,col:7,draft:['','','','','','','','',''],answer:''},{idx:17,lock:false, zone:2,row:1,col:8,draft:['','','','','','','','',''],answer:''},
        {idx:18,lock:true, zone:0,row:2,col:0,draft:['','','','','','','','',''],answer:'7'},{idx:19,lock:false, zone:0,row:2,col:1,draft:['','','','','','','','',''],answer:''},{idx:20,lock:true, zone:0,row:2,col:2,draft:['','','','','','','','',''],answer:'9'},{idx:21,lock:false, zone:1,row:2,col:3,draft:['','','','','','','','',''],answer:''},{idx:22,lock:false, zone:1,row:2,col:4,draft:['','','','','','','','',''],answer:''},{idx:23,lock:false, zone:1,row:2,col:5,draft:['','','','','','','','',''],answer:''},{idx:24,lock:false, zone:2,row:2,col:6,draft:['','','','','','','','',''],answer:''},{idx:25,lock:true, zone:2,row:2,col:7,draft:['','','','','','','','',''],answer:'2'},{idx:26,lock:false, zone:2,row:2,col:8,draft:['','','','','','','','',''],answer:''},
        {idx:27,lock:false, zone:3,row:3,col:0,draft:['','','','','','','','',''],answer:''},{idx:28,lock:false, zone:3,row:3,col:1,draft:['','','','','','','','',''],answer:''},{idx:29,lock:false, zone:3,row:3,col:2,draft:['','','','','','','','',''],answer:''},{idx:30,lock:false, zone:4,row:3,col:3,draft:['','','','','','','','',''],answer:''},{idx:31,lock:false, zone:4,row:3,col:4,draft:['','','','','','','','',''],answer:''},{idx:32,lock:false, zone:4,row:3,col:5,draft:['','','','','','','','',''],answer:''},{idx:33,lock:false, zone:5,row:3,col:6,draft:['','','','','','','','',''],answer:''},{idx:34,lock:false, zone:5,row:3,col:7,draft:['','','','','','','','',''],answer:''},{idx:35,lock:true, zone:5,row:3,col:8,draft:['','','','','','','','',''],answer:'5'},
        {idx:36,lock:false, zone:3,row:4,col:0,draft:['','','','','','','','',''],answer:''},{idx:37,lock:false, zone:3,row:4,col:1,draft:['','','','','','','','',''],answer:''},{idx:38,lock:true, zone:3,row:4,col:2,draft:['','','','','','','','',''],answer:'7'},{idx:39,lock:false, zone:4,row:4,col:3,draft:['','','','','','','','',''],answer:''},{idx:40,lock:true, zone:4,row:4,col:4,draft:['','','','','','','','',''],answer:'9'},{idx:41,lock:false, zone:4,row:4,col:5,draft:['','','','','','','','',''],answer:''},{idx:42,lock:true, zone:5,row:4,col:6,draft:['','','','','','','','',''],answer:'6'},{idx:43,lock:false, zone:5,row:4,col:7,draft:['','','','','','','','',''],answer:''},{idx:44,lock:true, zone:5,row:4,col:8,draft:['','','','','','','','',''],answer:'3'},
        {idx:45,lock:true, zone:3,row:5,col:0,draft:['','','','','','','','',''],answer:'6'},{idx:46,lock:false, zone:3,row:5,col:1,draft:['','','','','','','','',''],answer:''},{idx:47,lock:false, zone:3,row:5,col:2,draft:['','','','','','','','',''],answer:''},{idx:48,lock:false, zone:4,row:5,col:3,draft:['','','','','','','','',''],answer:''},{idx:49,lock:true, zone:4,row:5,col:4,draft:['','','','','','','','',''],answer:'4'},{idx:50,lock:false, zone:4,row:5,col:5,draft:['','','','','','','','',''],answer:''},{idx:51,lock:false, zone:5,row:5,col:6,draft:['','','','','','','','',''],answer:''},{idx:52,lock:false, zone:5,row:5,col:7,draft:['','','','','','','','',''],answer:''},{idx:53,lock:false, zone:5,row:5,col:8,draft:['','','','','','','','',''],answer:''},
        {idx:54,lock:false, zone:6,row:6,col:0,draft:['','','','','','','','',''],answer:''},{idx:55,lock:false, zone:6,row:6,col:1,draft:['','','','','','','','',''],answer:''},{idx:56,lock:true, zone:6,row:6,col:2,draft:['','','','','','','','',''],answer:'3'},{idx:57,lock:true, zone:7,row:6,col:3,draft:['','','','','','','','',''],answer:'5'},{idx:58,lock:false, zone:7,row:6,col:4,draft:['','','','','','','','',''],answer:''},{idx:59,lock:false, zone:7,row:6,col:5,draft:['','','','','','','','',''],answer:''},{idx:60,lock:false, zone:8,row:6,col:6,draft:['','','','','','','','',''],answer:''},{idx:61,lock:true, zone:8,row:6,col:7,draft:['','','','','','','','',''],answer:'1'},{idx:62,lock:false, zone:8,row:6,col:8,draft:['','','','','','','','',''],answer:''},
        {idx:63,lock:false, zone:6,row:7,col:0,draft:['','','','','','','','',''],answer:''},{idx:64,lock:false, zone:6,row:7,col:1,draft:['','','','','','','','',''],answer:''},{idx:65,lock:false, zone:6,row:7,col:2,draft:['','','','','','','','',''],answer:''},{idx:66,lock:false, zone:7,row:7,col:3,draft:['','','','','','','','',''],answer:''},{idx:67,lock:false, zone:7,row:7,col:4,draft:['','','','','','','','',''],answer:''},{idx:68,lock:true, zone:7,row:7,col:5,draft:['','','','','','','','',''],answer:'1'},{idx:69,lock:true, zone:8,row:7,col:6,draft:['','','','','','','','',''],answer:'8'},{idx:70,lock:true, zone:8,row:7,col:7,draft:['','','','','','','','',''],answer:'5'},{idx:71,lock:true, zone:8,row:7,col:8,draft:['','','','','','','','',''],answer:'2'},
        {idx:72,lock:false, zone:6,row:8,col:0,draft:['','','','','','','','',''],answer:''},{idx:73,lock:false, zone:6,row:8,col:1,draft:['','','','','','','','',''],answer:''},{idx:74,lock:true, zone:6,row:8,col:2,draft:['','','','','','','','',''],answer:'6'},{idx:75,lock:false, zone:7,row:8,col:3,draft:['','','','','','','','',''],answer:''},{idx:76,lock:false, zone:7,row:8,col:4,draft:['','','','','','','','',''],answer:''},{idx:77,lock:true, zone:7,row:8,col:5,draft:['','','','','','','','',''],answer:'9'},{idx:78,lock:false, zone:8,row:8,col:6,draft:['','','','','','','','',''],answer:''},{idx:79,lock:false, zone:8,row:8,col:7,draft:['','','','','','','','',''],answer:''},{idx:80,lock:false, zone:8,row:8,col:8,draft:['','','','','','','','',''],answer:''},
    ]
    }
];

export default problems;